config/routes.rb
Rails.application.routes.draw do
    mount ActionCable.server, at: '/cable'

    devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
    }

    resources :conversations, except: [:edit, :new, :create]
    resources :localizations, except: [:edit, :new, :create]
    resources :messages, except: [:edit, :new, :create]

    root to: 'conversations#index'

    post :send_msg, to: 'api#send_msg', as: :send_msg
    get :send_msg,  to: 'api#make_msg'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    # has_many :users
    has_many :messages, dependent: :destroy
    has_and_belongs_to_many :users

    def display_users(user = nil)
        (user.nil? ? self.users : self.users.where.not(id: user.id)).map do |user|
            user.first_name
        end.join(', ')
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :destroy]
  before_action :check_current_user, only: [:show, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = current_user.conversations
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end


  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.fetch(:conversation, {})
    end

    def check_current_user
      unless @conversation.users.include?(current_user)
        # TODO change message
        redirect_to :root, alert: "YOU CANT VIEW THIS DICK!!!!!"
      end
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<table>
    <thead>
        <tr>
            <th>People</th>
            <th colspan="1"></th>
        </tr>
    </thead>

    <tbody>
        <% @conversations.each do |conversation| %>
        <tr>
            <td>
                <%= link_to conversation do %>
                    <%= conversation.display_users(current_user) %>
                <% end %>
            </td>
            <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br />

<%= link_to 'New Conversation', send_msg_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_with url: send_msg_path do |form| %>
  <%= form.text_field :usernames, multiple: true %>
  <%= form.text_area :content %>
  <br/>
  <%= form.submit %>
<% end %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<div id="messages" data-conversation-id="<%= @conversation.id %>">
    <%= render @conversation.messages %>
</div>
<div id="send_form">
    <%= form_with url: send_msg_path do |form| %>
        <div class="form_body">
            <% @conversation.users.each do |user| %>
                <%= form.hidden_field :usernames, multiple: true, value: user.username %>
            <% end %>
            <%= form.text_field :content, placeholder: "[enter] to send message", rows: 2 %>
            <%# form.submit "send", id: 'send_button' %>
        </div>
    <% end %>
</div>

<script>
    $(document).on('ready turbolinks:load', function() {
        window.scrollTo(0,document.body.scrollHeight);
        $('#messages').scrollTop($('#messages')[0].scrollHeight - $('#messages')[0].clientHeight);
        registerChannel("<%= @conversation.id %>")
    });
</script>