config/routes.rb
Rails.application.routes.draw do
    mount ActionCable.server, at: '/cable'

    devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
    }

    resources :conversations, except: [:edit, :new, :create]
    resources :localizations, except: [:edit, :new, :create]
    resources :messages, except: [:edit, :new, :create]

    root to: 'conversations#index'

    post :send_msg, to: 'api#send_msg', as: :send_msg
    get :send_msg,  to: 'api#make_msg'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/localization.rb
class Localization < ApplicationRecord
  belongs_to :message
end

app/controllers/localizations_controller.rb
class LocalizationsController < ApplicationController
  before_action :set_localization, only: [:show, :edit, :update, :destroy]

  # GET /localizations
  # GET /localizations.json
  def index
    @localizations = Localization.all
  end

  # GET /localizations/1
  # GET /localizations/1.json
  def show
  end

  # GET /localizations/new
  def new
    @localization = Localization.new
  end

  # GET /localizations/1/edit
  def edit
  end

  # POST /localizations
  # POST /localizations.json
  def create
    @localization = Localization.new(localization_params)

    respond_to do |format|
      if @localization.save
        format.html { redirect_to @localization, notice: 'Localization was successfully created.' }
        format.json { render :show, status: :created, location: @localization }
      else
        format.html { render :new }
        format.json { render json: @localization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localizations/1
  # PATCH/PUT /localizations/1.json
  def update
    respond_to do |format|
      if @localization.update(localization_params)
        format.html { redirect_to @localization, notice: 'Localization was successfully updated.' }
        format.json { render :show, status: :ok, location: @localization }
      else
        format.html { render :edit }
        format.json { render json: @localization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localizations/1
  # DELETE /localizations/1.json
  def destroy
    @localization.destroy
    respond_to do |format|
      format.html { redirect_to localizations_url, notice: 'Localization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localization
      @localization = Localization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def localization_params
      params.require(:localization).permit(:message_id, :content, :lang)
    end
end

app/helpers/localizations_helper.rb
module LocalizationsHelper
end

app/views/localizations/_form.html.erb
<%= form_with(model: localization, local: true) do |form| %>
  <% if localization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(localization.errors.count, "error") %> prohibited this localization from being saved:</h2>

      <ul>
      <% localization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message_id %>
    <%= form.text_field :message_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :lang %>
    <%= form.text_field :lang %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/localizations/edit.html.erb
<h1>Editing Localization</h1>

<%= render 'form', localization: @localization %>

<%= link_to 'Show', @localization %> |
<%= link_to 'Back', localizations_path %>

app/views/localizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Localizations</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Content</th>
      <th>Lang</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localizations.each do |localization| %>
      <tr>
        <td><%= localization.message %></td>
        <td><%= localization.content %></td>
        <td><%= localization.lang %></td>
        <td><%= link_to 'Show', localization %></td>
        <td><%= link_to 'Edit', edit_localization_path(localization) %></td>
        <td><%= link_to 'Destroy', localization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Localization', new_localization_path %>

app/views/localizations/new.html.erb
<h1>New Localization</h1>

<%= render 'form', localization: @localization %>

<%= link_to 'Back', localizations_path %>

app/views/localizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @localization.message %>
</p>

<p>
  <strong>Content:</strong>
  <%= @localization.content %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @localization.lang %>
</p>

<%= link_to 'Edit', edit_localization_path(@localization) %> |
<%= link_to 'Back', localizations_path %>